//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditCardManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int AccountID { get; set; }
        public int CustomerID { get; set; }
        public string AccountPassword { get; set; }
        public System.DateTime OpenDate { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public decimal Balance { get; set; }
        public bool AccountStatus { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
