//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditCardManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCard
    {
        public string CardNumber { get; set; }
        public decimal CardLimit { get; set; }
        public decimal usuableLimit { get; set; }
    
        public virtual Cards Cards { get; set; }
    }
}
