//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditCardManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCard
    {
        public CreditCard()
        {
            this.TransactionInfo = new HashSet<TransactionInfo>();
            this.Customer = new HashSet<Customer>();
        }
    
        public string CardNumber { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public string Cvc { get; set; }
        public string CardName { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public bool isActive { get; set; }
        public string Pin { get; set; }
    
        public virtual CardInfo CardInfo { get; set; }
        public virtual ICollection<TransactionInfo> TransactionInfo { get; set; }
        public virtual ICollection<Customer> Customer { get; set; }
    }
}
