//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditCardManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Account = new HashSet<Account>();
            this.CreditCard = new HashSet<CreditCard>();
        }
    
        public int CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerSurname { get; set; }
        public string Email { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string PhoneCell { get; set; }
        public string PhoneHome { get; set; }
        public string PhoneWork { get; set; }
        public bool isActive { get; set; }
    
        public virtual ICollection<Account> Account { get; set; }
        public virtual ICollection<CreditCard> CreditCard { get; set; }
    }
}
