//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditCardManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Installment
    {
        public Installment()
        {
            this.TransactionInfo = new HashSet<TransactionInfo>();
        }
    
        public int InstallmentID { get; set; }
        public int NumberOfInstallment { get; set; }
        public int StartingMonth { get; set; }
    
        public virtual ICollection<TransactionInfo> TransactionInfo { get; set; }
    }
}
